version: "3"

services:
  backend:
    depends_on:
      - db
    build: ./backend

    volumes:
      - static:/static
      - ~/secret.txt:/secret.txt
      - migrations:/app/api/migrations

  db:
    image: postgres:11
    volumes:
      - dbdata:/var/lib/postgresql/data

  nginx:
    image: nginx:1.16
    depends_on:
      - backend
    volumes:
      - static:/static:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
      - "443:443"

volumes:
  static:
  dbdata:
  migrations:

