dist: xenial
language: python
python:
  - "3.6"
services: 
  - mysql
install:
  - pip install -r ./practice-app/backend/requirements.txt
before_script: 
  echo before_script
script:
  - cd practice-app/backend
  - python manage.py makemigrations
  - python manage.py makemigrations api
  - python manage.py migrate
  - python manage.py test
