dist: xenial
matrix:
  include:
    - language: python
      python: 3.7
      install:
        - pip install -r ./traiders/backend/requirements.txt
      script:
        - cd traiders/backend
        - python -m pycodestyle --ignore=E501 .
        - python manage.py makemigrations
        - python manage.py makemigrations api
        - python manage.py migrate
        - python manage.py test

    - language: node_js
      node_js:
        - "11"
      install:
        - cd traiders/frontend
        - npm install
      script:
        - npm run review
      cache:
        directories:
          - traiders/frontend/node_modules

#    - language: android
#      dist: trusty
#      jdk: oraclejdk8
#      android:
#        components:
#          - tools
#          - android-25
#          - build-tools-25.0.3
#      before_script:
#        - cd android/AppName
#      script:
#        - ./gradlew build connectedCheck

