dist: xenial
language: python
python:
  - "3.6"
services: 
  - mysql
install:
  - pip install -r ./traiders/backend/requirements.txt
before_script: 
  echo before_script
script:
  - cd traiders/backend
  - python -m pycodestyle --show-pep8 --show-source --ignore E501 .
  - python manage.py makemigrations
  - python manage.py makemigrations api
  - python manage.py migrate
  - python manage.py test
