version: "3"

services:
  backend:
    depends_on:
      - db
    build: ./backend
    volumes:
      - static:/static
      - media:/media
      - migrations:/app/api/migrations
    env_file:
      - ~/traiders_prod_env

  backendcron:
    depends_on:
      - backend
    build: ./backend
    command: bash run_crons.sh
    restart: always
    env_file:
      - ~/traiders_prod_env

  db:
    image: postgres:11
    volumes:
      - dbdata:/var/lib/postgresql/data

  frontend:
    build: ./frontend

  nginx:
    image: nginx:1.16
    depends_on:
      - backend
    volumes:
      - static:/static:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - media:/media:ro
    ports:
      - "18080:80"

volumes:
  static:
  dbdata:
  media:
  migrations:
