name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd traiders/backend
        pip install -r requirements.txt
    - name: Style check
      run: |
        cd traiders/backend
        python -m pycodestyle --ignore=E501 .
    - name: Test
      run: |
        cd traiders/backend
        python manage.py makemigrations
        python manage.py makemigrations api
        python manage.py migrate
        python manage.py test

